# src/main/resources/application.yml
storage:
  base-dir: "${user.home}/paperhub/pdfs"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: PaperHub_01

  datasource:
    #url: jdbc:postgresql://localhost:15432/paperhub?currentSchema=core
    url: jdbc:postgresql://3.38.5.129:5432/paperhub?currentSchema=core
    username: spring_user
    password: spring-pass
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20        # 인스턴스/DB 스펙 보고 10~30 사이
      minimum-idle: 5
      connection-timeout: 10000    # 10초. 너무 오래 안 기다리게
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: core
        show_sql: false
        format_sql: false



jwt:
  secret:
    key: "${JWT_SECRET:7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==}"

pinecone:
  apiKey: ${PINECONE_API_KEY:pcsk_4N174X_M87YqzLwgiiW79HgaqaS3o9jFGX5bwn7ZeM36UQwDWreqtUg8RkMwtWMiC42y2B}
  queryUrl: https://paper-keywords-ntuygv9.svc.aped-4627-b74a.pinecone.io/query   # Pinecone 콘솔의 Query URL
  namespace: ${PINECONE_NAMESPACE:}


aws:
  s3:
    bucket: paperhub01
    region: us-east-1
    base-url-style: s3

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini
